package homework.hw27.hwA;

public class Bread implements Thing{
    @Override
    public void action() {
        System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNXKK00KKNWWMMMMMMWWXK00000XXXXKxodOXNNWWMMWNXKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNNXXXNNNNNX0OkkkkkkxxdooodxkkkO00KOxoloollok00kkdoxxkkddxOKKKOkxxkxk0XNWMMMMMWNKKXXXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNXXK0kxdodddoodxddddddddoooollcclllcc::::cll;'',;;;cx0kxdooxkkkxdooddllodooloxxk00KXXXOdooxxkxxkOKNMMMMMMMWNWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWWNNKOxkOkddddoooolooddoc:clc:::ccccccc:::ccccc:::cccccllllc:;;:ldcclcclcloddolc:,,:cldxxxddxxdddxxxkxxxdldxookKNNNXX0xxOKWWWWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXKKK00kkOOOkxoodddooooooooddxxxxoccllllccc:::cloooooddooolc::lllodooooodo:':lllllloddolllooclooddodkkkkoclollcc::;;::coxxkOOxodxodO0K0OOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Oxdooooodxxxkkdlc:;coooddddoodddddooddxxxxkxollooddxxxxddxdddddlcloddc'.,cccllloddxxxxxxdooodxxdxoloooddc:ll:::::;;;;;cl:cxkxllddllxkO000kxddxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkxdodol::c:clodddxdoc;:;,;::;;;;clodddxxkkkxxdxkkkkkO00Okoclloollllooccodoc,..,:c::lodooooolllodxxdoollodoooooc;;::cclolloddkkooxOk;'cxddkO0XXNKOocloxKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOOkxdoc:;;:::::::ccllloddol:;:cc::cc;,,,;coddddxxkkxxoclllolccloooc;:cc:::::clcloo;.''',;;;;:::;;;;;;codolodddooodol:;;:cccldkKKOxddodxxkkOOxodxxkkkOKXKK0xlldxxOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNNXKOdlc:::::::;;:::;:loooolccclc:::::cllodkd:;;:odxxxxxkkO00d:::cddc;;::cccclc;,,;coddoo:...',,;;,,;;::;,;;cdoolloxxdooolc;;:loooodOXX0OdodddkkkkkxxkkxkkkxkOO00kxxkkkOkodk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNK0kkkxdlcllc:;::c:::::ccloooollcc:::ccc:clooddkkl;,,o0K00Okkkxdc:,'',,:c:;cclddooo:;;;:oxddol;..';,;;;;;;;;;,,:ldoooodxdool;,;;:cdkxdodxkkOOxlcoxkOOkkkkxxxxddxkdldOOOOOOxkOkxddxxxxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOOkddlc:;;:cll:::;:::;;::clllc:::::::;;::;cloooddxd:,;:;:ldodolc:;'.',,,,'',:lllooddoc;;;:ldddol:;,,,;;;;;::;;,,;codlcodddocc:;,,,,;clc::lxkkk0Oxoodkk00OOkkkkxdooodxdoxOkkx:;:dxdddxxxxkKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOdolc:::;,,;;::::::::::cloodddol:,'..',;;:;:ldoooddoc;;:c::::;,;c;''...,;;;,'':cloloodkd:;ccldoddc;;c:;;:::;;;;;;;;lolll::cllc;;;,,;,,,;;;:odooxkOOOkkOkO00OOxdkxxkOxooxkkOOkOkl:cdxodxkOkkO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOolc:;,,,;;:::::ccllllcclxkkkkkxdlc;',;;::clccooollc:;,:c:ccllc:;;,'.....;:;;;,,:cllllloxdcoolooccc,',::cc:;::;;;;;;cddllol:;;;;,,,,,,,,;;;:okx:;okkOOOkkxxkkOkkxodkkkkkkxxOOOkkkxxkkxoooodxxkOOxOXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0xoll:,';:;;;:::clodxdoooccloddoc::;,'';olllllolc:;;;,.';::cc::::;'....'.....';:::;,;:::ccccclooll:''..';::ccccc:;;::::odollc;,;'',,,,,,,,,;;;lkxoocokkkOOxdodxkOxxxlokxkO0K0kdokOOkOOkkkdodolodxkdccdxOXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKK0xxxxxdlclc::::codxxkxdc;;;::;,,'..';:;:dkxdollccc,';;,.':cc::;,,,'.............;,,;:;;:;,,'';loool;....;:::cccc:;;;:c:cdxlcc:'''',,,,,;;;,,,;:xkoooldkkkkkkddxxkkodkxkxxkO0KOxolxOOO00kkxxxkxdxkkkkoodookKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kO0000000koc::cldxkkkkxd:'.',,,,,,,,;:::cdkOOkocc::;,;::;;;;::;;;'..''..............',,,;;'....;clllc,'..,:;:clllcc::::ccodl;;;'.',;;;;;,,,;;;,;oOkxkxxkkxkOkxddxdxdldkOxddkOO0kdxxxkkkO00OOkkkkkkOXXOxkOkxxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOOOkO0KKKKOo:;:loxkkkkkxdc,'';:::ccc;,;::;cdkkkdlc:::::::::,'..,,;,....................''.';'....;cclllc,...;:;::cclllc:;;:codc,;,..';;,,,;;;;;::cd00kOOkkOOkxxxkkddkkxddkOOkxxOO0KOkkxxkkkOOOOOkkkxkKWNKkkOOOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0xodk0KKKK0K0o'';cdxkOkkdl;'.',;:cllll:,,;c:;cddlc:::::::;;;,.....'.........';;::;,,'.....''.',;,,',ccclc:;....,:::;;:::::;;;:cdoc:;'..';;;;;;::;;:lx0NX0O0OOOxxxddkOkxOkxxxkO0OkkxooxOOkxddxxxkOO000kxONWXOkxxdxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdolc::clooooooc::cccllllc:,..',;;;:cllc:,',:c:::c::::::::;;;,,'...','''''',::;cc:cllc,''',,;'...'::;,;llol;,'.. .,::;;:;;;::c:::ldo::,...,;:::;;:;;:coxKNKOOkkOkxxxkkxkOOOkxkOO0OxxkxoodkkkkkxxxdxOO0XKOOKWN0kkkkxxxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdolccc;,:cllccccc::clcclc:;;;;,,;;:;;;:lc;'.';:c::::::::::::;,'...',,,,,,,,,,;:cccc:cdxddoc:;;;'...;::;',coo:,'... .;;;::::::::::::cooc;'...,;;;;;;:;,:coxOKOxkkdxxxkkkxoxkxxkkkOOkOOxxkkOOOk00OkxodxxxO00O0XN0kOkxkkxddxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOdoool:;:;;lddxxdddol:;::::cccc:::c:ccc:;;,'',;;::::::::ccc:;;;'..',,'.',;;;;,,,,;:ll:cddddxkOOOxl,''';:;,'';cc,....  .,;;::::;;,;;;:cldo:,....,::::::,..,cddoxocxkooxxddxkkkxdddxOOxxkxkxxOxodOKK0OkxxkxxkkkkkkkkkkxkkxkkxddxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0dlclllc::;':dxxxxxddl:',::;;clll:;;cll:;'..',:clccc:::ccccc:,''...';,...,;;;;;;,,,;:c:;lxolooodkO00kdc,''''''.,:;..... .,::::,,,..''',lllc;'.. .,:::::,..;lx0KOdoxkkocxOxdxkOkoooooxkxxxdkkkOxoldOOOkOkxxddxxxkdld0kxxxkkxxxxkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWOlcccc:;:::;'.ckkkxxxxdl:,;:::lodool:;:::;,,,;:ccllcc:;;;cllc:,'''','.''.',,,,,,,;;;;;:c;':dolllloodxxxOOo,''''..'c;...   .',,,'.....';:;;:::;... .,::;::;coddxkKX0k00OkdxxoxOkkkkkkkkkxxxxddxdxkxxxddxkkkxkkdxkdoddx00OOkkOkxooxkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxlllolccc:;'..ckOkkkxdol;',;cooddodol:::;,.''',;::::::,,;;;;,'',,,,'...''..''',:cc:;;;;::,,lc:cllllooloodxdc;;;',::'...    ..'.....,codxo:;cc;... .,:;;;:lloodxO0NNKO0O0OkxdxkkxOKKOxxkkkxooddooxkxdddxOOOkxxxxxdddxOOkkOxdkkxo:cokOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxoooooolcc:;;,';dOOOkxdo;.';:lddddddddl:,.....',;,,,;:;'';,''.'';:;'...'''';cccllc::::::coodxdlc::clllcccclxxc,'.';;'....   ..,;;;;:oddddxdc:;,...  .::,,:clodxkOKNNKOk000OkkkkxxOKX0xdkOOxooxkxdkOkooxk00OOkxxkxxxookOkkkkxxkko;';oxkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOddddoodxxo:;,''',,cdkko;'..',;lxxdxxxdlcc;'';,',;;;;,,;,';;,,,''';c:;,,;:ldxxxddxdccollc;ldddxxkxdl::clc:clodxdc:,,,,'....   .,,;:::ldddooddl,','... .:c::lloxkOO0KXNKOkOOOkxxkOxxO0KOkxkO0kdxxkkkOOkxddxO0OOOOOOOkdlcxOkdxxddxdxo:;codkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWMN0dloxxxddxkOd;'...',,',;;,..';,..:xkxxollcc::c:;;'';;;,,;::::cc:;,,;cccccclxkxdooodxdlldddc,:dddddxxkkxc;;;:loooodxOd:;,'....   .';;;;;oxxdoodxd;..'.   .;:;:cclodxxkkO0OOkxxkkxxxkkkOOOOkkkkOkxxxkxxxkkkxodkOOOO0Okxkxlcxkkkxdlxkdxkxdoddx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMNkol:lxkkxxxkOd,.':cc::;'.';;;::'..;oxdccclccc:::;,',,,',;:c:cccllc;;:cccccoxkxdoooddxoloddxo;,ododdddxkkko,';llllloxOxl;,'.........,,'',okxddddxxc....  ..';;::;:cllc:;;cdkxdxxdoxxxkkxkKXXKKOOOkkxkkkxddkkkxk0K000ko:cdddxxkOOxooxxxxkkkkddONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMKdolcokkkxxkkOd,'cxxddol:,;c::;,,;:cllollllcccc;;,'',;'.';:c;:cccc::cclc:::oxxdoooddxdccoxxxd:':oddddddxxkxl,.;lllcoxkxo:,......,ooc:,'',lxxddddxxc'..... .':::ccclodoc::cok0OkxddoddxxxOXNNWWNX0OOkxkOkxxxxxxdk000Okdc:ldxkkxxOOxloxkkOOkkxdkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMNklcccokOkxxxkko;:oxxxxxxxlc:cc:;,;:clccc:cc::c:;;::ccc:,,;;;,'::::::::ccc:cdxddoddxxdc:ldxxkxc,,lddddddddxdo:',:lloddkxo:'......:dxxdol;';oddooodxo,.... . .;;;clcldddoc:;:lxkOkxdldkxxO0KKkOXWNX0OkdxxdooddxxodkOOkxxoloxxxkxxxkxxxxkOKN0kxddkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWWNOc::::lkOkkkkkko:ldxxxxkxdollool:,':cccc:cclccc;:ccloddoolc;,'';::c:;,,,collodddooxxoc:ldxxxkxc;,,lxdddooddool;',:loooxxl;.......,ddddddl;':ddollodo;...... .';,;cccoddoc;;;:oxxkkxololodk0Kd:o0NNXkxxxxkxodxkkoloxkxxkxdxOOkxxodkxodxkXWWKxddodkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMWKkxo;,',;cxOOkkkkxlcoddxxxxdddooollc,';cccc::llccccclloododxxxdl:;;;collc;,;:lollodddoc;:ldxxxxxd:;;;;cdxdoooooolc,,;;:cldoc;'......;ododdool,,lolcccol:,........',;;:clool:;;:ldkkxxkOkdcclx0Kk:,l0NN0kxdxk00xoxOkkxxxddxkxxk00kkkxOOxddONWWKkxoooxdokNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMWXOxolc:;..',lkOOkkkdllxxddddddxxdoool:,',:ccc;',:;,:ccodooloxkkkkxdl;;lddoc::;,,:clooooc;;coxkxxxdl:c::;;cldooooollc;;;;;;:ll;'.......:ooooooll:,:lc::cloc;....'ll;'',;:cccc::;:cccdkkxk00dcoxxk0Kd:cdXNKOkoox00xodxkkkkdodxdoloxxkkkxdkkxxONNXK0xoloddox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMNOdxkkkxdl;'.;okOxxxlldxdoollloxxdooolc;',:lc;,.',,;ccclooodxxkxxxxdl:cdxxdl:clc,.'codxxoccldxxxxdl::clc:::::ccllll:;,;:;;;;cc;'.......;olllllllc,;cc:::coc,'....cxdo:''',,;;;,',;;,:dxxkkOOdoxkkOXKxod0NK0OxddkOxoooxxxkdodxdoloxdxkxddxkkx0XKKK0xooodddxxkXWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMW0xkkOOOOOko:,;okxxo:lxxdollllldxdoooll:,,:c:;'',,'':c::ldoodddddddolclxkxddooodl,';cloolc:coxxxdl::ccccccc::;;::::;,;;;;;;;:c:,'......'cllloolc;,,;:::::lc,'.....ldddc'........',,,;coxxkkOOddxkOKXX0O0XKOkkkkkkxdooxxxdxxxkkxdoodxxdlloxOkO0KKKkdodxxdloxdOWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMWXkkkOOOOkkkxl,,lol;,cddddooooldxddoool:,,;;,,'.''..';,';cccodooooolccoxkxddddddoc,;ccc:;'.':ddol::cc:::cc:::ccc::c:::;;;;;;:;,''.........,:c:;;,,,;;;;;;:c;'.....,odoo:........',,',:coxkkkkdodxkOKXNNXXKOkkkxk0Oxloxxdllxkkxkko:lxOx:,:oxOO0K0OxxxkOOxodkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWK0OOOOOkkkkkd:';::;cdkkkxdoollodxddol:,..'',,,;;;;;,.'',;clolllllcccoxkxdddxxxxo;';ccc:,,;;:c:;;:cc:::::;;;:ccccc::::::::;;;''.....  .. ..,,,''''',::;,,;;'......:oool;',.....''..';;;ldxxxdddxkOKKXXXXKOkxxkkOOxodkkddodOOxxOkccokx;';cokOO0OkkkkkkkxxkO000WMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMN0O000Okxxkkkxl;:cccoxkOkxddol:;lddoc;,',;:::::;;;::;;:;,,,::cccccclooddddddxxxo;.',,,,;:c;:clc:cccc::::;,;;:::c::cc::::;;;,''... .   . .,,,;,'....,::;,;,'.......:lloc;,'.....'',,,;loooddooxxk0000OO0OOkxxxxdkxooxkkxolxOkxxkdoodkl:clokOxxkkxxxkkddxkkOOk0WMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWKdokOOOkkxxkkkxl;;ccclddddool:'',:c:;;:cloddol::;:c:;;:lc;,,',;::::lolodxdxxxxdc,...',,::;;:clllllccccc:;;:;:::c::::;;::;,,;,'..  ...   .':ccc::;;,',;;;;;'........:llc:;'',..,;;:cccdkxollldxdxkO000kkOkkOkxolooodxkOOxddkxxddxoddddxkdodkkxxkkxxkxkOkxddxxOXWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWOc;coxOOkxkkOOko;,;:cccclclc;:loll:,,:ok00Okkxdoddoolc:::;;;,,''''';lcldxxdxxdo;'.',;;::;,,,,;::llcccccc::::::::c::::;;;;,,;;'.......   ..cl:;;;;;,,'.',;,.........'coc:;,'..';;;:cc:cdkdloodxxxOkdxkxxxkOOkxoldxdodxkO00kxddddxddddloxdodxkkkkxxxkkkkkoloxkOKWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNkc:c:;coxkkkOOkl;;;;;:c::cccokkxdxd::x0KK00OOOkxdddoddol;,;;;;;'.''';:clddoolc;'.';cc::::;,,:lc;;;;::::::::::::::::;;;;;,:c::;.....      .,::;:;;;,,,',::,''.........cl:::'.';::;;;:ccoxdcodooxkkkoodoodxOOkxxdkOxdxxxk0KOkkkxxxkoldoldxddddxkxodxkkxxxoc:oxOKXWMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMXdclc;;;;cloddoc:;:;;;;::::oxkkkkxxdldOKKKK00OOkxl:coooodoc:cccc:;;,'',,;:c::;,,,,;clllllc::lkOkdc'.,,',',;;;,,,,,,'.'',;:cll:'.....       .,;;:::;;,,,;::::;'....... .;:;,'';::;::;:cllxkdodddxxdddololdOOOdoxkkOxdkOdxkOkxxkOkxxdlddodkxodxxkxodxkkxxkxo:;lkkOXWMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMXdlol::::::::::::clooc;,;;;cxkxkkxxdodOK00000Okxo,..:ooooddlc::::::;,''''''''.',:clloolllccoO00Okd:,;;;;;,'''.....'''',,::ccc;'......      ..,,,;;;;;,,',:;,,.......   .,',,;::;;;:::ccldkxddooddloxxddddxkkddxxkOxdkOkxxxxdddxdoxkxxxdoddoxkkkxodxkkxxkkdc;codxk0XWMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNklooc::;;;:;;:c:loddolc:,':xkxxxxdoc:odlcdO0Oxo:;:;;;coddolc::cc:;,,,,,,'';,',cooooolllcclk000OOkl;;:::cc;'',;::cccccccc;;:;'.........    .;;,'',;;,''.,c:,........   ...;:::;;;;;:::cloxkxkxddxxxxdxddxxxxkkkOOOkkkkkxodddxdxxdxOOxxkdooxOOkOkxxkkxxkkkxlcodxxkkOKWMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNklcc::,'';::;:::loooooolc,;oxxxxdol;;,',,cxkxolodxdoc,;lolc:::c:;,,,,,,,,,::;cooolllllcccok00OOOxo:;:ccol,,:cllllccc:codl:c;.........     'cc;;,..'....':;,........... ..clc:;;;;:::cccldkxxxxxkkkxdxxolddxdllxOOOOxdxoclloxxxkxxxxxkOxlcoxO0OOkkkkxdxkxxkddxxxxddOXWMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNklcc:;'.,:cccc:;:lollloolc;:ldxol:,;:;,,cxkxxxdddddddc;;ccc::cc:;,,,,,,,,,;:coolllllllllclkOOOOkxl;:ccccc:clllllcclcclokdc:;'....... .    .:c;;;,''...';lc;'..... ...   .cl::;;;;::cccclldkkxddxxdkkkklcddodl;okOOOdokkllodkOOOkxxxdxkkdloxkkkkO0Okxxxkddxxkkkkkxkk0XWMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWOlc::;,';cllllc:;:lolclllc:;;cc:;,;lc;,,cxOOkxdoooooool;;::::::,,,,,;,,,,',;cccc::cclllllcokkkkxdc,,;,,;:cclllllcccccldkxc;;'......   ..  .,c:;::;,'.';cll:,........... .;c:;,;;:::cc:::cdOkxxddkO000Ododo::c;cdxkkxdOKxcldxk0Kklldddkkoc:lxkdxO0OxdxkkxxkkO00000OkO0NMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWOc;clc;,;clccllcc::cllclcc:;;c:cccool:;,;dOOkxooooloool:;:::cc:,,,,,,,','',:llcc::;;;:c::;;oxxdol,.',,;:cllllllllccccclolcc;............   'ccc::;,',;ccll;............ .,::;;;;:ccc::;;:okOOkkxx0KK00kxxdc;;;:oxkOO0K0xloooxOOkdodxxkxl;,:oddxxkkxdxkxxkk00KXNNXKK0OKWWMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWOl::cc;,,:lllllllc:;clcccl:;:c::lc::cc:;;:lodxdoolclool:;:::::;,,::,,,''';cllcc:::::,',;:cclool:;'';;;:ccllllllllcc:::;;,,;,'......   ..   'cllc:;,,:ccc:c;'...  .....   '::::;;::::cc:::lk00OkkdxKXKK0kkkd:;cldkkOkk00kdxxxkxdxxdxxxxkdc::lxxddxxkOkkkxkO0KXNWWWNXK00XWMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNOocllc::,;cooooool:,:ccccc;,:c::::;;::cc;;;:oxdoollloolc::::;;:;;:c::;,';lccc:::::cc,':odxxddoc:;,,;::;:cccllllllc::cc:clc:;'......  ...  .;llc:;:;,,:cccc:;,'............:::clc::::ccc::cd0KOOkxdOKKK0kxkkocloddxoloxkxddxxkxlloodxkkkdc:clddddxxkxxkkxxkO0XNNXKKNNX0OKWMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMW0dolllc::;;cdddddl:;:c::::;;:cc::::;,;:c::;:odoooooooool;',;;;;:cc:;;;,;ccccc:::::c:;:oxkkkxxdllc;,;cc;;:::cccc::;:lollool:;'...... ..    .,::,,;c:,';looooc;'.......... .;l:;cc::;:ccc:::lx00kxxxxk00OkxkOOxddxxxlcoxkxdxkkkxl:cddxkkkxdddxdoooddddkO0OxxxkKNN0xkKNNK0XWMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWKxdolllcc:;,;:cloc:::c:ccllc:ccc:;;;;::;;:;;lxdooddodddo;',,,,,:lc::;;:cclcccc:::cc;:odxkkkxdoooccclool::;:::;,,;;;cc:cldo:,'....... .    .;;,,,,;;,':odoodl;,'...... ... 'lc;;;;:;;:c:::::lxOOkxddxkkkkkkkkxxkkkOd:cdOkxxkdddolcdxxddxxxxxkxdodxxxddkOOxdox0XNNKO0XNXXWMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNOdooolc:;;;:looooollc;;:cll:::cc;,,,,;;;;::;cdddddddxxxc'',,,,,,;;::;::clolcc:::::;;cddxxxxdollcllloodoolcllllccc:,',;:ldl:,'........ ....'cccc:;;,':odoodxo:,,'......... .;c;;;;;,;:cc::::ldxkOkdxxkkxxkkxdooddkOkocokOkxdodkkxdoododxOxok0kxdxxxxdoxOkdddxOKXNNNXXNKKNMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMW0dollc;,,:ldddoolllllc:ccc::cc:;,,:cloddxddooddddxxxxxl;:clooooooolc:::cllc:::;:c;';lodddxdolccl:cooooooollllllllc;'.',clc,'..........  ..,lllcc:;;:dddooodxl,''...... .   .';;;:;,',;:;;,;:cdkOdldxxxxxxkxddxkkkkkxolxOOOkdldkxxdoooodkOO0K0kxxodddxO0OkxxxkO0XNNNNNKO0NWMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWKdllc,',cddodddoollllccccc:::;,;ldxkxkkkkkkkxxocldxxdlloxxxxddddddddoc;;;;;;;;:ll:,:loooooolollllloooooolccllllolc:,'..':;'.......... .   'clcc::;;lxddooodxl,''.........   .,:;,,;::ccc:::cox0OkdddxxdxxkxdxkOOkxxkdodxkkkxxddxddddl:lkO0XXKkxkkkxdkO0Oodxddxx0XNNNXKOk0NWMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMW0olc:;';oxxxdoollloocccllc:;,;ldkkkkkkkkkkkkxxoc;;lllodddddddddoooollc;;;:clcccll;;:clcclooooollloooooolccclloollc:;;:::;,'............   .;:::::;:dxddooodxo:'''........  . 'lc;:cllcccodkOKXXK00kxxxdodxxdoxOOkddxOkdxxkkkOOddxxxkdlodk0XXKOxxkxolxxkkolxxdxdk000KKOddxOXWMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMWWWWW0occc:,:oodxdollloolccclc;',coxxxxkkkkxxxxxxddl;.,clldddddddddoooolc:::ccodolccllc:;;:cllllollllllloolcc::clloolcc;,:lolc;,,'....  ....   .';;;::;cdxdooooddoc,''........  . .cdc;:cccldk000KXNN0OOddxxdooxkxxkOOxdxkkddxkOkOOdcoxxdodxkk0X0kkkxxkxxddxkkkkxxxolxxkkkxdddxk0NMMMMMMMMMM\n" +
                "MMMMMMWWWWWWWWWWWWWWWKxllc:',clooooolclllolc:;',cooodddxkkkxdddddoc;'..;clodddooooolccc:;:llloooollooooolcloolclooolcoolloc:llllllllc;,,,;::c;,;;,..........    .'''',,:dddooooddl:,''..... ...   .'oxl:cclxOOO000KNWX0OxddxkdlodddxkkkkkxxodkkkkxOkl:coodxddk00kxOOkOOOkxddk0XKOxxdllddxxxxdoookNMMMMMMMMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWXkooc;,,;ccccccccodoool:;,;ccclooddxxxdlllcc:;,,,'',;;clllcc:;;;::;:clllooodlcllloooclolooolllllclllllllllol;;:;;:cllcclc;;;'......       .':;'.'':ooooloddoc;'.'..... ...... .:xxooooxkxk0000KNNK0kxxxxo:lxkxxxxdxxkxooxxxkkkkxl:cloxdcdOkdkOxxOOOkxxxOKXKkooxxxdoooxkddddxKWMMMMMMMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWW0dlllccc:;;;;cooddoolcc:,,::cc::ccccc:;;;;cccclc::::;,,;;;::clodolccllllodolllclloc::cllllllcllllc:lollooc;:clooooollooc;,,'......       .,cc::c::cllllodlc:;'..............  'dOkdloxddkOOOOO0XXKOxxxko:okkkkxookOkxoldkkxxkdoolcldddodOxlddodxkkkkxkO0KkocokOkdoddxkxdxkxONWMMMMMMMM\n" +
                "WWWWWWWWWWWWWWWNWNWWNNXxooollll:;,coooddolc:;,;::cool;'';;;,;;:cccloooooool::::ldxxkkxdocclooooooldollol:,,;clloodlclllcclllolc:cooooddddooll:'''''......       'cc:;;;;::::col:cl;''........... .. .ckxollooodxxxkxxk0Okxxdxxdxkkxxxdx00kxdcokkkkxccoocoxocooxkxdxkxkkxxkkkOOOxdxkOkxxkkxxxddxOkkKWMMMMMMMM\n" +
                "WWWWWWWWWWNNNNNNNNNNNNXxollllll:;;looodooc;,';c:;;:c:;,;:::;;;;clcllloololllccoxkkkxxdolc::loooolloolll:,;;;;;coooolcccccllllc:loolodxxxxdolc,..'........   .. .,ccc:;;;::::lolldo:,'...........    .;ddolcccllolcccldkOOxxkxxxxkkxdxkkkkxdxookxkkkdlloodxdlllok0Oddk0OookkddxxdoxOOkkkOkxxxddxxdokXWMMMMMMM\n" +
                "WWWWWNNNNNNNNNNNNNNNNNXklllc::c:;clllodolc:,,::;;;;::;,;::;;;;,:ccc;:c:clllolldddxxdoolc::::::looollcll;,;;;;;;clooocclllllllccooooodddddddoc;'.'............. .;:;;;:ccclollooooo:,'...........     .:loc;;ccccc:;,:okOkddxxxdodxxdxxxkOxdxxxxxkkxkoldxxkkdc:ldkkxdOKKkxkxlcoddxxxkOkkxxxkkxdoc:cd0NWMMMMMM\n" +
                "NNNNNNNNNNNNNNXXXXXXXXKdcllc;,cc:cccllclooc::::::::::cc:;::;;,;:ccclllllllllclooooooolcclolc;;cddoc;cllc,,,,,;;c:clcloolcloolccloooooooooodlc:'.................':::;;:loooooooooo:;'....... ... ..  ..,::;;:;,,;;;;;:oxOOxdddolodxkxkdoxdoddkOOOkxxddxkxdkxoooooddx0XKOxxxocldkkddxkkkkkkxxdxxocldx0NMMMMMM\n" +
                "NNNNXXXXXXXXXXXXXXKKKX0oclc:;;cc;:cccc:clo:;cc:cclc:::ccc:::,,:llllclllolllccllooolllldxxdoc:;coolccllllc;;:cccc::lcllooooocclccoooddololool:,'''.............. .:c;;:ccloodoc;:loc;,.............. ...'::;;,,,:cc:::::lx00Odloddxkkxxd::::cldkOkxdxkxxxdddxxxooddxOKKOkkxkOkddkkkxxxkOkxxxxkkkxxkxdkXWMMMMM\n" +
                "XXXXXXXXXXXKKKKKKKKKKK0dlll:;::::cllclc;cl:;c:cclllcccclll:;',cllolcllcllolc:;:lolcclxxxddolc:coocclolllllooooloolllllololl:,:cccloooooollllc,................  .:c::ccloc,;loccool:;'.............    .;c;';ccccc:c:::clx00kxkkxdkOkxxoooooodxxkxdxkxxdoddddddxkkk000kkkxk0OkkkkkOkkkkxxxkOkkkkkxddxKWMMMMM\n" +
                "XXXXXXXXXKKKKKKKKKKKKKKkl;;:cc:;:lllll;,:oc,;:::cclllccllloc,;cllolcllllllc::;,;::;cdxxdddoolclollllloc,',colllooolollllllllccl:,;ccccc::::::,.'...'''...... ....:c::cloo;..;ollodlc;'.............     'l;;ccccc:clc:::coOK0kdkkxkxxkxxOkxddxkkkkkxxxxoloddddxxxxOOOOkkkxxkkxxkxxkOkkxxkkkxxkkkxxdx0NWMMMMM\n" +
                "XXXXXKKKKKKKKKKKKKKKKKKOdc:::::::cc:c:,;llc;;;;;:ccclllllllc:;;cclccclllllc:lc,,,,:oxddddooolcloccllldo,':lllloolloolllllccllllc:;::::::lc;;,'''.',,'''..........;:;:;cloc,';looodl:;'.............     .;:;:c:::::cc;;;:oOOkkdxkxxxdxkkkxddxxkkkOxodxdooddddodxddxkxxkxkxoddodxddkkkxdxxxxodkkxdxkOXWMMMMMM\n" +
                "XXXKKKKKKKKKKKKKKKKKKKKKOdlcclc:,;cc::;;c:;:c:;,,;:ccllloolc:;;;clccllllllc::;,;;;ldddddoooocclolclooooccllooooollllloollc:ccc:;:c:cccclodl;'''..',,'''..........,clllllllollc:cool;,'......  .....      .':::::c::::;:llokkdxxdxxxkxddxxkkkxkkkkkkxxdxxxxdollldkkxdxdxxxoloxxddxxxxxkkkkkkxkkxdxOKXWMMMMMMM\n" +
                "XXXXKKKKKKKKKKKKKKKKKKKK0xl:;clccc:;:cc;cc,',clc;;,;::clllc:',::cc::clllllc:,',;;;lddddoooooccloooolloddoolllooooc:cooolcc:;;::;clclllllool;....',,'''... .......;ooolllcclo:,;clooc,'.............       .;:;;;,;;;clloolcdkOxddxxkkxxdddxkxdkOOkkkdodxkkkxl:lxkOkkkxddxddxxxxxkOxx0KK0OOkkkO00XWWMMMMMMMMM\n" +
                "XXXXXXXXKKKKKKKKKKKKKKKK0ko:;:cc:;,,:llccc:,,:cllc:::;;;;:c:;,,;::cclllllccc:;;;,':ddooooool:cloodolclooloollooccllcloolcc;,col::clllc;;,:l:'..',,,''............;oc:llclclc...,;;:c;'.........  ... ..   .;c::;:cccloooolldkkxxxkkxxkxddooddddxxkkxxxxxxxxxdoxOOOkkxxkxdxxlclxk00kk0KKKKOOOKXNWWWMMMMMMMMMM\n" +
                "NNNNNXXXXXXXXKKKKKKKKKKKKKOxdlc,''..,::ccccccccccccllc:::cccc:;;::cccllllc:cc;;;,.,lollllc:;;clllolclllc:looolllcllcccccc::lddl:,;c:,'''.',;'...'''..............'l:,:llolll,,:::;:c;,'...........      .  .:olccllloooddddxxxxOxxkkkOOxxxxxxddxkkxxxOkkxdddddxxkkkddxxxxkkdldk000OkkO0OkkO0KXNWWMMMMMMMMMMM\n" +
                "NNNNNNNNNNNNXXXXXXKKKKKK000Okxoc;,'..',;:cc::ccc::cccc:cccc:;:cccc::cclccc:;;;;;;,;clllc:;:::cccclllllclcclolcllllc:cclolllollc::cc:,,;;;;,;,.........   ....... .loccllolllc:lc;;cc:;'...........     . .. 'lllollolclodolokOO0OxkkkO0OxkkxxdddxdodkOxxdooooddxdxkxxkkxkkOK00xxxddkxoloxOKXNWWMMMMMMMMMMMMM\n" +
                "WWWNNNNNNNNNNNNNNNNXXXXXKK00Okxdolc:;;;;,,;:;;:c:::ccccc::c:;:cccc::;;::;;;;;lllolcc:::::ccc::;;:cclccccllllcccccl:;clooollcc:;:ccll:,;cloc;'..........  ..... . .cdolccllllcclccccc:;'..........        .  ..:ccc;;clccooooxO0K0kdxdxOkddxxxxxxkkxxkOOOkooooddxkOkxxxddkkkOkoc::ok0OkOKXNWWMMMMMMMMMMMMMMMM\n" +
                "WWWWWWWWWWWWNNNNNNNNNNNNXXXXKKK00Okkxxxdoollc::::::ccc::::::cccc:;,,;;::::;,;coooollc;;:cc::c::::cc::;:cccllcccccc:;:cllllc::;::lllll:,',::;'..........  ..      .'llcccllll::loolll:,''............     .. ...,;;;,:lol::lllox0XKOxdddxddxxdxxdx00OkO0KkoodxxddxOOOkddxOkdllccldkKXNNWWMMMMMMMMMMMMMMMMMMMM\n" +
                "WWWWWWWWWWWWWWWWWWNNNNNNNNNNNXXXXXXKKKK000OOkxdolc:;;;,;:::cccc:;'',:::ccllc::clollll:;:ccc::::::::::cclllllclccccc:::ccc::;,;:clllcllc;,;:;'..........          ..;clcclcclllllllol:;,''.....     ...     ....':clccollccllc;:x0XXOxdxxxxxxxoxkxkOkkO0KOxdxkkxddOOOOdlokxlldxddkOKNWMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNXXXXXKK00Okxdlc:;;;;;:::;''',:ccccccccc:;:ccllol::cc:::::::cccccccccllllllcl:::c::;,,,',:lllccccc:cc;............       ....,:lcccc:cloolllooc;;,''..............   ..  .:llllllllcccc;,lkKXXOdxxxkkkOkxxxxdxkkO0OkOOOOxdk00kxxxxxxxkkOOOkOKWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNXXXXXKK0Okxxdoolc:;,,::::ccccc:,,,;:::;;::ccc:::::cc:clcclcclcccc:::c::;;;;;;;,,:llcccccccl:'........     .........'cc:::cclcllooolol:;,,''.........  ...      .;olllllcllcclcclk00XKddxxkkkOkxdxkxkxxxxkOO0KKOOXXKOkO0KKXNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKK00Okxxdoollcc:,,;;,'.'',,;::::::::::::cclcc::;;;,,;:::;;;;;;;:;;:clcccccclc;,'......  .....     ..,lcccc::c::cllllol:;,,,'..........  ..       .ll;;cc:llc::ccldOO0X0xddxkkxddxxdxkkxxdk0KKXKxx0K00KNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKK00Okkxdolcc::;,,,',,,;;:::;::;;;,,:c;,'',,,;;;;;;;;;;;;cccc:cc:::;'.............    ...,llc::;;;,';:cclloc;,'..............         .;oc:cooooc::clllokOKKkoddddxxkkkddxxxxkOKXXKkdkO0XXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWNNNNNNNNNNNNNNNNNNNXXXXXXXKK00Okxdoolcc:;;;,,,''...',,'''...'';:::::;;;:::;:;;::;,'....................':ccc:;'....':c:cll;'.............   ..    ...':oolllclccloooodxkkOxccclddxkkOOO0OkOOkOK000KXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKK0Okxdollc::;,,'''.....,;;:clooddollc:;;;;,,...............',,,,;:::cc::;,'''';::clc,'.'''....         .....''',cllllcclllloodxxxkOkl::lxxdxkOkxxkkkkxk00KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKK00Okkxddoolcc:;;;;;;:cllolllool:,'............,;:::::cc:;::::;;;,,',;:c:,,''''...       ....'''',,,,;:llcccccllooodxxxkkxoclddxkkkxxkkkkOKXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNXXXXXKKK00Okxdolcc:;;,;;;:ccccc:::::::::::cccccccclccc:::;,',,,,;;;::;,'....    ....''',,,,;;;;;;;clcccc::clloooxddkkxdooodkxdxkkkOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNXXXXKK00OOOOOOOOOOkkkkkxxxddooooooooooolllc:;,',,;::;;cc;''........'',,,;;;;;:::::::codolccccclllllodokOxxOOdoodxk0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNNNWNNNNNNNNNNNNNNNNNXXXXXKKKKKK000OOkkkkxxxxxdoc:;;;;;;;:::::;,''''',;;;;:::::::::ccccccccclllc;;clcllllodddkOOOkddkOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXKKKKK00OOkxxdolc::::cclooooddoooollllllllllllllllllllc::cc;:lllloodkOOkk0KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXXXKKKKKKKKKK0000OOOkkkxxxdddoooooooooooolc:;,,;:cloodxO0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWNNNNNNNNNNNNNNXXXXXXXKKKKK000OOOkkkxxxdddolc,',,;:ldxOKXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNXXXXXXKKK00OkkkkO0KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
    }
}
